# Generated by Django 2.2.5 on 2019-09-14 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190911_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 15, 5, 34, 173808, tzinfo=utc)),
        ),
    ]
